const names = [
  "Limon Kg",
  "Portakal Kg",
  "Starking Elma Kg",
  "Deveci Armut Kg",
  "Sıkma Portakal File Kg",
  "Granny Smith Elma Kg",
  "Greyfurt Kg",
  "Çilek Paket 400 Gr",
  "Kavun Kg",
  "Karpuz Kg",
  "Golden Elma Kg",
  "Santa Maria Armut Kg",
  "Ananas Adet",
  "Nektarin Kg",
  "Şeftali Kg",
  "Patates Kg",
  "Soğan Kg",
  "Domates Kg",
  "Salatalık Kg",
  "Çengelköy Salatalık Paket 500 Gr",
  "Çarliston Biber Paket 300 Gr",
  "Kokteyl Domates Paket 500 Gr",
  "Mantar Paket 300 Gr",
  "Sivri Biber Paket 300 Gr",
  "Kırmızı Biber Paket 300 Gr",
  "Patlıcan Kg",
  "Sarımsak File 200 Gr",
  "Şeker Domates Paket",
  "Kabak Kg",
  "Salkım Domates Kg",
  "Dolma Biber Paket 300 Gr",
  "İstiridye Mantarı Paket 250 Gr",
  "Biber Köy Paket",
  "Şili Biber Paket 150 Gr",
  "Pembe Domates Kg",
  "Baby Patates File",
  "Pancar",
  "Bostan Patlıcan Kg",
  "Fasulye Kg",
  "Bakla Paket",
  "Kaliforniya Biber Kg",
  "Haşlanmış Mısır Paket",
  "Pancar Paket",
  "Havuç Paket 350 Gr",
  "Marul Göbek Adet",
  "Kıvırcık Adet",
  "Kırmızı Lahana Kg",
  "Roka Adet",
  "Dereotu Adet",
  "Tere Adet",
  "Reyhan Adet",
  "Taze Soğan Adet",
  "İthal Muz Kg",
  "Avokado Adet",
  "Çağla Badem Paket 200 Gr",
  "Erik Papaz Paket 400 Gr",
  "Kereviz Kg",
  "Maydanoz Adet",
  "Yerli Muz Kg",
  "Yaban Mersini Paket 125 Gr",
  "Marul Adet",
  "Semizotu",
  "Sivri Kıl Biber Paket ",
  "Böğürtlen Paket",
  "Domates Salkım Kg",
  "Hıyar Badem Paket Kg",
  "Hıyar Kg",
  "Bakla Sakız Kg",
  "Eurofresh Yıkanmış Yaprak Marul 250G",
  "Yerli Ceviz Kg",
  "Havuç Beypazarı Paket Kg",
  "Eurofresh Yıkanmış Hazır Ispanak 700 G",
  "Erüst Mini Mini Domates 250 G",
  "Badem Kabuklu Kg",
  "Muz Yerli Kg",
  "Roka Demet",
  "Patates Taze Mini Kg",
  "Freshes Haşlanmış Kırmızı Küp Pancar 200 G",
  "Verita Kumkuat 200 Gr",
  "Muz İthal Kg",
  "Kabak Sakız Kg",
  "Spesiyal Soğan File Kg",
  "Mantar İstridye 200 G",
  "Osmaniye Kabuklı Fıstık 800 G",
  "Salata Kıvırcık Adet",
  "Zencefil Kg",
  "Erüst Salata Karışık 150 G Adet",
  "Erik Malta Kg",
  "Portakal Sıkma File Kg",
  "Biber Kırmızı Kg",
  "Spesiyal Patates File Kg",
  "Erüst Deniz Salata 125 G",
  "Komşu Keçiboynuzu 500 G",
  "Çilek Kg",
  "Eurofresh Yıkanmış Beyaz Lahana 400 Gr",
  "Erüst Dağ Salata 125 G",
  "Verita Çarkıfelek Passıon Fruıt 3’Lü Paket",
  "Armut Deveci Kg",
  "Domates Kokteyl Kg",
  "Salata Maskolin 150 G Erüst",
  "Excelente Altın Çilek Paket 100 G",
  "Elma Starking Kg",
  "Patlıcan Kemer Kg",
  "Domates Pembe Kg",
  "Freshes Haşlanmış Mini Patates 200 G",
  "Komşu Kabuklu Fındık 500 G",
  "Elma Granny Smith Kg",
  "Biber Çarliston Kg",
  "Eurofresh Doğranmş Karışık Akdeniz Salata 150G",
  "Tasconi Kuru Domates 125 G",
  "Verita Taze Hindistan Cevizi Adet",
  "Kivi Kg",
  "Atom Salata Adet",
  "Kuzu Kulağı Demet",
  "Excelente Zerdeçal Paket",
  "Verita Pitahaya Adet",
  "Ceviz Kabuklu Kg",
  "Pazı Demet",
  "Alaşehir Asma Yaprağı (Ci) 455 G",
  "Nar Kg",
  "Soğan Taze Demet",
  "Fasulye Çalı Paket Kg",
  "Reyhan Demet",
  "Şeftali Nektarin Kg",
  "Elma Fuji Kg",
  "Brokoli Kg",
  "Bezelye Araka Kg",
  "Gurme 212 Marineli Kuru Domates 150G",
  "Verita Yer Kirazı (Altın Çilek) 100 G",
  "Elma Amasya Kg",
  "Biber Sivri Kg",
  "Tatlı Domates 250 G Paket Adet",
  "Yurtalan Asma Yaprağı 500 G",
  "Kavun Kırkağaç Kg",
  "Elma Golden Kg",
  "Kabak Taze Siyah Kg",
  "Eurofresh Doğranmış Kırmızı Lahana 300 Gr",
  "Si&ha Salamura Bamya 530 G",
  "Kayısı 250 Gr Adet",
  "Armut Santa Maria Kg",
  "Karnabahar Kg",
  "Patates Tatlı İthal Kg",
  "Erüst Kişniş 25 G",
  "Taze Sıkılmış Portakal Suyu 330Ml",
  "Greyfurt Kan Kg",
  "Migros Pırasa Paket Kg",
  "Pırasa Demet Adet",
  "Rozmarin 25 G",
  "Taze Sıkılmış Portakal Suyu 750Ml",
  "Elma Granny (Pazar) Kg",
  "Biber Köy Usulü Kg",
  "Eurofresh Yıkanmış Kıvırcık Marul 150 Gr",
  "Mantar Kestane Paket 350 G",
  "Komşu Çıtlamış Fındık 500 G",
  "Elma Pink Lady Kg",
  "Nane Adet",
  "Fesleğen Demet",
  "Fasulye Ayşe Kadın Kg",
  "Komşu Yer Fıstığı Tuzsuz 500 G",
  "Biber Dolmalık Kg",
  "Turp Kırmızı Demet",
  "Patates Kumpirlik Kg",
  "Ağaçaltı Antep Fıstığı 150 G",
  "Elma Starking (Pazar) Kg",
  "Semizotu Adet",
  "Soğan Arpacık Kg",
  "Domates Kurusu 100 G",
  "Elma Pink Lady (Pazar) Kg",
  "Portakal Kan Kg",
  "Ispanak Kg",
  "Eurofresh Doğranmış Göbek Salata (Parça) 200G",
  "Tasconı Marine Kuru Domates 100 G",
  "Verita Böğürtlen 125 G Paket",
  "Havuç Çıtır 250 G Paket Adet",
  "Biber Dolma Amerikan Kg",
  "Freshes Haşlanmış Kırmızı Pancar 400 G",
  "Verita Lımes 3'lü Paket",
  "Hass Avokado Adet",
  "Lahana Kırmızı Kg",
  "Lahana Beyaz Kg",
  "Tasconi Organik Yemeye Hazır Kuru Domates 100 G",
  "Erik Papaz 250 Gr Paket Adet",
  "Yaban Mersini 125 G",
  "Pancar Kg",
  "Domates Kokteyl 500 G Erüst",
  "Tasconi Yemeye Hazır Kuru Domates 100 G",
  "M Life Organik Elma Kg (Ort. 400 G)",
  "Çağla Badem 250 G Paket Adet",
  "Patlıcan Bostan Kg",
  "Yerli Kuşkonmaz Paket 300 G",
  "Gurme212 Asma Yaprağı 455 G",
  "Kiraz Yer (Altın Çilek) 100 G",
  "Yer Fıstığı Kg",
  "Freshes Koçanda Tatlı Mısır 2 Adet Paket",
  "Garliko Kurutulmuş Domates 200 G Paket Adet",
  "Osmaniye Kabuklu Yer Fıstığı 500 G Adet",
  "Kavun Sera Kg",
  "Lolorosso Adet",
  "Agrotalya Haşlanmış Kırmızı Pancar 500 G",
  "Hindistan Cevizi Adet",
  "Komşu İğde 500G Paket",
  "Excelente Zencefil 250 G Paket",
  "Yerli Papaya",
  "Verita Taze Dilimlenmiş Hindistan Cevizi 125 Gr",
  "Verita Granadilla Adet",
  "Eurofresh Yıkanmış Marul Mix Salata 170 Gr",
  "Verita Redberry 125 Gr",
  "Verita Yemeye Hazır Mango Adet",
  "Verita Nar Tanesi 125 G Paket",
  "Verita Demirhindi 225 G",
  "Excelente Demirhindi Paket 225 G",
  "Excelente Kumkuat Paket 150 G",
  "Excelente Yemeye Hazır Mango Adet",
  "Verita Gurme Yemeye Hazır Avokado Adet",
  "Verita Yaban Mersini Blueberry 125 G",
  "Verita Kuşkonmaz 300 G Paket Adet",
  "Excelente Blueberry 125 G",
  "Enginar Adet",
  "Excelente Lime 3'lü Paket 195 G",
  "Kayısı Kg",
  "Kültür Mantarı 400 G Paket",
  "Deniz Börülcesi Adet",
  "Roka Mini 125 G Erüst",
  "Yassı Şeftali Kg",
  "Biber Acı Şili Kırmızı Kg",
  "Taşköprü Sarımsağı File Kg",
  "M Life Organik Ceviz Kg",
  "Erik Papaz Kg",
  "Domates Cherry 250 G Erüst",
  "Mantar Izgaralık 500 G",
  "Verita Zerdeçal 100 G Paket",
  "Erüst Taze Baharat Saksılı Adet",
  "Soğan Frenk - Şiniklav 25 G",
  "Hatay Enginarı Adet",
  "Semizotu 150 G Erüst",
  "Biber Meksika 150 G",
  "Patates Yeni Mahsul Kg",
  "Soğan Kuru (Yeni Mahsul) Kg",
  "Erüst Fesleğen Taze 25 G Paket",
  "Pratik Kültür Mantarı 400 G Paket / Adet",
  "Kiraz 500 G Paket Adet",
  "Kuşkonmaz Excelente Paket",
  "Erüst Hıyar Badem 500 G Paket Adet",
  "Mango Adet",
  "Yemeye Hazır Avokado 2'li Paket Adet",
  "Kereviz Sap Adet Erüst",
  "Ispanak 700 G Erüst",
  "Erüst Mini Mini Mix 250 G",
  "Erüst Soya Filizi 125 G Paket",
  "Erüst Kekik 25 G",
  "Erüst Marul Çıtır 100 G",
  "Mısır Taze Adet",
  "Müpa Mantar Shiitake 200 G",
  "Kuzu Kulağı Paket 150 G Erüst",
  "Erüst Salkım Kokteyl Domates 300 G Paket Adet",
  "Böğürtlen 125 G",
  "Biber Sivri Kıl Kg",
  "Excelente Yemeye Hazır Avokado 2'li Paket",
  "Verita Frambuaz 125 Gr",
  "Avokado 3'Lü Paket Adet",
  "Üzüm Tarsus Kg",
  "Tuzlu Yer Fıstığı Jumbo Promosyon 300 G",
  "Erüst Yedikule Mini 4'lü Paket",
  "Migros Kiraz 500 G",
  "Kiraz Lux Kg",
  "Kiraz Kg",
  "Ahududu 125 G",
  "Fasulye Barbunya Kg",
  "M Life Organik Patates Kg",
  "Erüst Girit Kabak 500 Gr Paket Adet",
  "Erik Angelica Kg",
  "Yerli Zerdeçal 100 G Paket Adet",
  "Erüst Ispanak Mini 150 G",
  "M Life Organik Patates Mini Kg",
  "Karpuz Mini Kg",
  "M Life Organik Havuç Kg Paket (Ort. 450 G)",
  "Karpuz Çekirdeksiz Kg",
  "Erüst Mini Mini Hıyar 250 G",
  "Kırkağaç Kavun",
  "Üzüm",
  "Ananas",
  "Mandalina",
  "Portakal",
  "Sıkmalık Portakal",
  "Finike Portakalı Sıkmalık",
  "Greyfurt",
  "Yerli Muz",
  "İthal Muz",
  "Kivi",
  "Granny Smith Elma",
  "Starking Elma",
  "Golden Elma",
  "Yeşil Elma",
  "Gala Elma",
  "Deveci Armudu",
  "Santa Maria Armut",
  "Ayva",
  "Yaban Mersini",
  "Yemeye Hazır Avokado",
  "Verita Dilimlenmiş Hindistan Cevizi",
  "Kokteyl Domates",
  "Cherry Domates",
  "Domates",
  "Yerli Tohum Vitrin Domates",
  "Kahvaltılık Domates",
  "Salkım Domates",
  "Çengelköy Salatalık",
  "Salatalık",
  "Erüst Atıştırmalık Mini Hıyar",
  "Sivri Biber",
  "Kapya Biber",
  "Kabak",
  "Patlıcan",
  "Limon",
  "Lime",
  "Havuç",
  "Mini Patates",
  "Kızartmalık Patates",
  "Kuru Soğan",
  "Karnabahar",
  "Brokoli",
  "Pırasa",
  "Kereviz",
  "Kırmızı Lahana",
  "Kırmızı Turp",
  "Mantar",
  "Taze Zencefil",
  "Sarımsak",
  "Soyulmuş Sarımsak",
  "Erüst Ayıklanmış Sebze Tabağı",
  "Bee Chef Pratik Mini Şarjlı Doğrayıcı",
  "Portakal Sıkmalık",
  "Kuru Soğan Kg",
  "Salata Kıvırcık",
  "Sarımsak 250 Gr",
  "Havuç Kg",
  "Dereotu Demet",
  "Çarliston Biber Kg",
  "Nane Demet",
  "Elma Granny Kg",
  "Salatalık Çengelköy 500 Gr Paket",
  "Kırmızı Biber Kg",
  "Dolmalık Biber Kg",
  "Malta Erığı Paket 400 Gr",
  "Örgü Sarımsak 500 Gr",
  "Galya Kavun Kg",
  "Kurutulmuş Çiçek Bamya 100 Gr",
  "Mantar 300 Gr Paket",
  "Salamura Asma Yaprak",
  "Amigo Dalından Kuru Üzüm 500 Gr",
  "Amigo dalından Kuru Üzüm Antep Karası 250 Gr",
  "Amigo Dalından Meyve Mıx 250 Gr",
  "Amigo Dalından Kuru İncir 250 Gr",
  "Amigo Dalından Kuru Kayısı 250 Gr",
  "Amigo dalından Kuru Kayısı Gün Kurusu 250 Gr",
  "Quru Kurutulmuş Ananas",
  "Quru Kurutulmuş Portakal",
  "Amigo Medjoul Hurma 300 Gr",
  "Sayınlar Rabbi Hurma 300 Gr",
  "Maydanoz Demet",
  "Malta Eriği Paket 400 Gr",
  "Avokado İthal Adet",
  "Can Erik Kg",
  "Limon Lamas kg",
  "Fuji Elma Kg",
  "İthal Muz kg",
  "Çilek kg",
  "Valensiya Portakal Kg",
  "Yemeklik Patates kg",
  "Kayısı kg",
  "Soğan Kuru kg",
  "Yaban Mersini Blueberry 125 g",
  "Salatalık kg",
  "Domates Pazar kg",
  "Sıkma Portakal kg",
  "Patlıcan Kemer Pazar",
  "Starking Elma kg",
  "Salkım Domates kg",
  "Golden Elma kg",
  "Çarliston Biber kg",
  "Şeftali  Kg",
  "Kıvırcık Salata Adet",
  "Kavun Galya Kg",
  "Havuç kg",
  "Granny Smith Elma kg",
  "Domates Şeker 250  g",
  "Deveci Armut kg",
  "Kanlı Greyfurt kg",
  "Çengelköy Salatalık kg",
  "Kavun Kırkağaç kg",
  "Sakız Kabak kg",
  "Malta Erik",
  "Kivi kg",
  "Sivri Biber Kg",
  "Mantar 300 g",
  "Finike Gurme Portakal kg",
  "Göbek Salata Adet",
  "Zencefil Taze kg",
  "Taze Soğan Demet",
  "Armut Deveci Gurme",
  "Organik Yerli Muz kg",
  "Bezelye",
  "Armut Santa Maria kg",
  "Kokteyl Domates kg",
  "Elma Starking Gurme",
  "Dolma Biber Kg",
  "Çilek Paket 500 g",
  "Zerdeçal Paket 150 g",
  "Çalı Fasulye Kg",
  "Amasya Elma kg",
  "Köy Biberi kg",
  "Elma Granny Smith Gurme",
  "Salatalık Çengelköy 500 gr Adet",
  "Tamarind Demirhindi 225 g",
  "Zencefil 250 g Adet",
  "Kırmızı Lahana kg",
  "Domates Kokteyl 500 gr Adet",
  "Organik Portakal",
  "Pembe Domates kg",
  "Limon Organik kg",
  "Kapya Biber 400 g",
  "Verita Ahududu Frambuaz 125 g",
  "Mantar İstiridye 200 g",
  "Verita Böğürtlen Paket 125 g",
  "Beyaz Lahana kg",
  "Lime 3'lü Paket",
  "Patates Kızartmalık File",
  "Can Erik 500 g",
  "Pancar kg",
  "Organik Mandalina kg",
  "Karnabahar kg",
  "Bostan Patlıcan kg",
  "Nar Organik kg",
  "Kapya Biber kg",
  "Greyfurt Organik",
  "Pırasa kg",
  "Verita Dr. Blue Yaban Mersini 125 g",
  "Kereviz Yapraklı Kg",
  "Verita Redberry-Frenk Üzümü 125 g",
  "Pomelo adet",
  "Dilimlenmiş Taze Mango 125 g",
  "Pazı Adet",
  "Avokado Gurme Yemeye Hazır Adet",
  "Ispanak kg",
  "Yaban Mersini 125 g Adet",
  "Taze Hindistan Cevizi",
  "Enginar Soyulmuş 5'li",
  "Mango Gurme Yemeğe Hazır Adet",
  "Brokoli  kg",
  "Çarkıfelek 130 g",
  "Domates Yerli kg",
  "Hindiba",
  "Salatalık Çengelköy Paket 300 g",
  "Armut Santa Maria Gurme",
  "Kuşkonmaz 300 g",
  "Kayısı 500 g",
  "Organik Avokado ",
  "Soyulmuş Sarımsak 100 g",
  "Erik Anjelika",
  "Patates File  Kg",
  "Razaki Üzüm kg",
  "Kıl Biber kg",
  "Çekirdeksiz Üzüm Kg",
  "Renkli Dolma Biber kg",
  "Kestane Kuzu -Orta",
  "Antep Karası Üzüm kg",
  "Fındık Turp Demet",
  "Pitahaya Ejder Meyvesi Adet",
  "Brüksel Lahana Paket",
  "Siyah Üzüm Kg",
  "Mantar Izgaralık 1000 g",
  "Çarkıfelek Meyvesi 3 Adet",
  "Kabak Siyah Kg",
  "Dut Kara Kg",
  " Dilim Mantar 400 g",
  "Hünnap kg",
  "Fesleğen Adet",
  "Elma Fuji Gurme",
  "Taze Patates Paket",
  "Elma Kırmızı Organik",
  "Kara Lahana ",
  "Limon Enterdonat kg",
  "Karışık Akdeniz Salata 150 g Adet",
  "Elma Golden Gurme",
  "Ayva Gurme",
  "Yeşil İncir Kg",
  "Kereviz Sapı Adet",
  "Tatlı Patates İthal kg",
  "Kuru Sarımsak Kg",
  "Bakla kg",
  "Alabaş Turp Adet",
  "Domates Sosu Kavanoz 590 g",
  "Delimatoes Güneşte Kurutulmuş Domates",
  "Paket Ispanak 700 g",
  "Organik Pırasa kg",
  "Havuç Siyah",
  "Organik Havuç",
  "Tatlı Patates Yerli kg",
  "Bal Kabağı Kg",
  "Çin Marulu",
  "Brokoli Organik",
  "Eurofresh Yıkanmış Kıvırcık Marul 150 g",
  "Bal Kabağı Soyulmuş (1200-1700 gr)",
  "Kuzu Göbeği Mantarı Kurutulmuş 30 g",
  "Borozan Mantarı Kurutulmuş 35 g",
  "Enginar 4'lü Şişe Kavanoz 370 g",
  "Kereviz Kavanoz 930 g",
  "Bamya Kızartmalık Kavanoz 800 g",
  "Kanlıca Mantarı Kurutulmuş 35 g",
  "Erüst Mini Mini Domates 250 Gr",
  "Erust Taze Baharat (Rozmarin, Kekik, Adaçayı) ",
  "Tombul Bamya Kavanoz 530 g",
  "Enginar Büyük Kavanoz 930 g",
  "Enginar Küçük Kavanoz 600 g",
  "Soya Filizi 125 g Adet",
  "Taze Fesleğen",
  "Salata Maskolin Adet",
  "Erüst Kokteyl Domates 500 gr",
  "Erüst Mini Ispanak 150 g Adet",
  "Semizotu 150 G Adet",
  "File Soğan kg",
  "Verita Taze Meyve Salatası 200 g",
  "Biberiye 25 gr",
  "Erüst Kişniş Adet",
  "Erüst Baby Roka 125 g",
  "Erüst Mini Yedikule Adet",
  "Erüst Çıtır Marul 100 g",
  "Sığır Dili Mantarı Kurutulmuş 35 g",
  "Sarıkız Mantarı Kurutulmuş 35 g",
  "Börülce Fasulye kg",
  "Organik Dereotu",
  "Taşköprü Sarımsak Örgü kg",
  "Organik Maydanoz",
  "Kabak Süs Mix ",
  "Erüst Mini Mini Hıyar 250 Gr",
  "Organik Patates kg",
  "Siyah Sarımsak 65Gr",
  "Taze Fesleğen Adet",
  "Pancar Organik",
  "Mısır 3'lü Paket",
  "Kayseri Patlıcan kg",
  "Salatalık Organik",
  "Organik Sivri Biber",
  "Kemer Organik Patlıcan",
  "Fençel",
  "Cin Biber 100 g Adet",
  "Domates Cheery Organik",
  "Eurofresh Yıkanmış Pırasa Havuç 750 g",
  "Bal Kabak Hokkaido Kg",
  "Eurofresh Yıkanmış Yaprak Marul 250 g",
  "Eurofresh Fresh Mix 160 g",
  "Eurofresh Doğranmış Göbek Salata 200 g",
  "Kumpirlik Patates Kg",
  "Eurofresh Yıkanmış  Brokoli 300 g",
  "Kıvırcık Organik",
  "Biber Dolmalık Organik",
  "Çengelköy Organik Salatalık",
  "Kornişon Salatalık",
  "Organik Sarımsak",
  "Eurofresh Yıkanmış Karnabahar 500 g",
  "Eurofresh Ispanak 700 g",
  "Eurofresh Doğranmş Karışık Akdeniz Salata 150 g",
  "Organik Domates kg",
  "Lahana Kırmızı Organik",
  "Soğan Gümüş Salam kg",
  "Mantar Beyaz 400 g",
  "Kereviz Organik",
  "Organik Kuru Soğan",
  "Karnabahar Organik",
  "Erüst Kuzu Kulağı 150 g",
  "Eurofresh Yıkanmış Marul Mix Salata 170 g",
  "Eurofresh Karnabahar Pirinç 400 g",
  "Eurofresh Yıkanmış Beyaz Lahana 400 g",
  "Eurofresh Brokoli Pirinç 350 g",
  "Eurofresh Yıkanmış Kış Bahçesi 400 g",
  "Kabak Organik",
  "Bamya",
  "Eurofresh Ayıklanmış Barbunya Havuç 500 g",
  "Eurofresh Temizlenmiş Yıkanmış Fasulye 500 g",
  "Zencefil Ezmesi 90 g",
  "Bal Kabak Midi Adet",
  "Sarımsak Ezmesi 90 g",
  "Lahana Organik",
  "Mantar Shitake 200 g",
  "Soyulmuş Arpacık Soğan 250 g Adet",
  "Soyulmus Arpacık 500 g Adet",
  "Kurutulmus Acı Biber Paket",
  "Kurutulmus Dolma Biber Adet",
  "Kurutulmuş Dilim Domates",
  "Kurutulmuş Dolmalık Patlıcan Adet",
  "Adaçayı Demet",
  "Lavanta Demet",
  "Kurutulmuş Trüf Mantarı 10 g",
  "Kekik Demet",
  "Mimi Kurutulmuş Yenilebilir Çiçekler Menekşe",
  "Mantar Kestane 350 g",
  "Taze Enginar (Temizlenmiş)",
  "Urla Sakız Enginar Dolmalık ",
  "Barbunya kg",
  "Siyah Karpuz kg",
  "Beyaz Üzüm Kg",
  "Soyulmuş Haşlanmış Pancar 500 G Adet",
  "Taze Fasulye kg",
  "Agrotalya Tatlı Mısır 400 g",
  "Taze Patates",
  "Sarımsak Taze Baş Kg",
  "Ahududu Paket 125 g",
  "Zerdeçal Paket 100 g",
  "Kayısı",
  "Çekirdeksiz Karpuz kg",
  "Mini Karpuz Kg",
  "Papaz Erik Gurme",
  "Taze Mısır Açık Adet",
  "Armut Deveci Gurme Kg",
];

const sidebarNames = [
  {
    main: "Elma",
    sub: ["Starking", "Granny Smith", "Golden", "Fuji", "Amasya"],
  },
  {
    main: "Greyfurt",
    sub: [],
  },
  {
    main: "Limon",
    sub: ["Lamas", "Organik", "Enterdonat"],
  },
  {
    main: "Portakal",
    sub: ["Sıkma", "Kan", "Finike", "Valensiya", "Organik"],
  },
  {
    main: "Armut",
    sub: ["Deveci", "Santa Maria", "Finike", "Valensiya", "Organik"],
  },
  {
    main: "Çilek",
    sub: ["Altın"],
  },
  {
    main: "Kavun",
    sub: ["Kırkağaç", "Sera", "Galya"],
  },
  {
    main: "Karpuz",
    sub: ["Mini", "Çekirdeksiz", "Siyah"],
  },
  {
    main: "Ananas",
    sub: [],
  },
  {
    main: "Nektarin",
    sub: [],
  },
  {
    main: "Şeftali",
    sub: ["Yassı"],
  },
  {
    main: "Patates",
    sub: [
      "Baby",
      "Taze Mini",
      "Spesiyal",
      "Tatlı İthal",
      "Kumpirlik",
      "Yeni Mahsul",
      "Kızartmalık",
      "Organik",
      "Yemeklik",
      "File",
      "Yerli",
      "Organik",
    ],
  },
  {
    main: "Soğan",
    sub: ["Taze", "Spesiyal", "Demet", "Arpacık", "Frenk", "Kuru"],
  },
  {
    main: "Domates",
    sub: [
      "Kokteyl",
      "Şeker",
      "Salkım",
      "Pembe",
      "Kuru",
      "Tatlı",
      "Cherry",
      "Pazar",
    ],
  },
  {
    main: "Salatalık",
    sub: ["Çengelköy", "Kornişon", "Organik"],
  },
  {
    main: "Biber",
    sub: [
      "Çarliston",
      "Sivri",
      "Kırmızı",
      "Dolma",
      "Köy",
      "Şili",
      "Kaliforniya",
      "Kıl",
      "Amerikan",
      "Meksika",
      "Kapya",
      "Cin",
      "Organik",
    ],
  },
  {
    main: "Mantar",
    sub: [
      "İstiridye",
      "Kestane",
      "Kültür",
      "Izgaralık",
      "Shitake",
      "Kuzu Göbeği",
      "Borozan",
      "Kanlıca",
      "Sığır Dili",
      "Sarıkız",
      "Trüf",
      "Organik",
    ],
  },
  {
    main: "Patlıcan",
    sub: ["Bostan", "Kemer", "Kayseri", "Kurutulmuş", "Organik"],
  },
  {
    main: "Sarımsak",
    sub: [
      "File",
      "Soyulmuş",
      "Örgü",
      "Kuru",
      "Taşköprü",
      "Siyah",
      "Baş",
      "Organik",
    ],
  },
  {
    main: "Kabak",
    sub: ["Sakız", "Taze Siyah", "Girit", "Hokkaido", "Bal", "Organik"],
  },
  {
    main: "Fasulye",
    sub: ["Çalı", "Ayşe Kadın", "Barbunya", "Börülce", "Taze", "Yıkanmış"],
  },
  {
    main: "Bakla",
    sub: ["Sakız"],
  },
  {
    main: "Mısır",
    sub: ["Haşlanmış", "Koçanda", "Tatlı"],
  },
  {
    main: "Pancar",
    sub: ["Kırmızı", "Soyulmuş", "Organik"],
  },
  {
    main: "Havuç",
    sub: ["Beypazarı", "Çıtır", "Organik", "Siyah"],
  },
  {
    main: "Marul",
    sub: ["Göbek", "Kıvırcık", "Yıkanmış", "Çin", "Çıtır"],
  },
  {
    main: "Lahana",
    sub: ["Kırmızı", "Beyaz", "Brüksel", "Kara", "Organik"],
  },
  {
    main: "Roka",
    sub: ["Mini", "Demet", "Baby"],
  },
  {
    main: "Dereotu",
    sub: ["Demet", "Organik"],
  },
  {
    main: "Tere",
    sub: [],
  },
  {
    main: "Reyhan",
    sub: [],
  },
  {
    main: "Muz",
    sub: ["İthal", "Yerli"],
  },
  {
    main: "Avokado",
    sub: ["Hass", "İthal", "Organik"],
  },
  {
    main: "Erik",
    sub: ["Papaz", "Malta", "Anjelika", "Can"],
  },
  {
    main: "Kereviz",
    sub: ["Yapraklı", "Organik"],
  },
  {
    main: "Maydanoz",
    sub: ["Demet", "Organik"],
  },
  {
    main: "Yaban Mersini",
    sub: [],
  },
  {
    main: "Semizotu",
    sub: [],
  },
  {
    main: "Böğürtlen",
    sub: [],
  },
  {
    main: "Yaban Mersini",
    sub: ["Yerli", "Kabuklu", "Hindistan", "Organik"],
  },
  {
    main: "Zencefil",
    sub: ["Taze"],
  },
  {
    main: "Keçiboynuzu",
    sub: [],
  },
  {
    main: "Kivi",
    sub: [],
  },
  {
    main: "Kuzu Kulağı",
    sub: [],
  },
  {
    main: "Zerdeçal",
    sub: [],
  },
  {
    main: "Pazı",
    sub: [],
  },
  {
    main: "Nar",
    sub: ["Organik"],
  },
  {
    main: "Brokoli",
    sub: ["Organik"],
  },
  {
    main: "Bezelye",
    sub: ["Araka"],
  },
];

// export default names;
export default sidebarNames;
